---

- name: install deps
  sudo: yes
  apt:
    name='{{item}}'
    state=installed
    update_cache=yes
    cache_valid_time=3600
    force=yes
  with_items:
    - 'autotools-dev'
    - 'automake'
    - 'autoconf'
    - 'autoconf-archive'
    - 'make'
    - 'libtool'
    - 'libgtest-dev'
    - 'libgflags-dev'
    - 'libgoogle-glog-dev'
    - 'libboost1.55-all-dev'
    - 'libjemalloc-dev'
    - 'liblzma-dev'
    - 'libsnappy-dev'
    - 'liblz4-dev'
    - 'libevent-dev'
    - 'libdouble-conversion-dev'
    - 'libunwind8-dev'
    - 'libssl-dev'

- name: Sync soure from git
  git:
    repo='https://github.com/facebook/folly.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/folly'
    update=yes
    recursive=yes
    version='efdf227'
    force=yes

- command: autoreconf -ivf
  args:
    chdir: '{{goobly_cache_dir}}/folly/folly'
    creates: '{{goobly_cache_dir}}/folly/folly/configure'

- shell:
    CC=/usr/bin/gcc-5 \
    CXX=/usr/bin/g++-5 \
    ./configure --with-pic --prefix="{{third_party_dir}}"
  args:
    chdir: '{{goobly_cache_dir}}/folly/folly'
    creates: '{{goobly_cache_dir}}/folly/folly/Makefile'

- command: make -j{{ansible_processor_vcpus}} install
  args:
    chdir: '{{goobly_cache_dir}}/folly/folly'
    creates: '{{third_party_dir}}/lib/libfolly.a'
